<?php // this is an autogenerated file - do not edit (created Tue, 18 May 2010 00:15:23 +0200)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'sampleresponse' => '/classes/response.php',
         'sampleresponseexception' => '/classes/response.php',
         'samplerequest' => '/classes/request.php',
         'sampleviewinterface' => '/classes/viewinterface.php',
         'samplefileupload' => '/classes/fileupload.php',
         'samplefileuploadeexception' => '/classes/fileupload.php',
         'samplecontroller' => '/classes/controller.php',
         'samplefrontcontroller' => '/classes/front.php',
         'samplefactory' => '/classes/factory.php',
         'sampledatabase' => '/classes/database.php',
         'sampledatabaseresult' => '/classes/database.php',
         'sampleerrorcontroller' => '/controller/errorcontroller.php',
         'samplesearchcontroller' => '/controller/searchcontroller.php',
         'samplehomecontroller' => '/controller/homecontroller.php',
         'sampleentrycontroller' => '/controller/entrycontroller.php',
         'sampleimpressumcontroller' => '/controller/impressumcontroller.php',
         'samplelogincontroller' => '/controller/logincontroller.php',
         'sampleregistercontroller' => '/controller/registercontroller.php',
         'sampleerrorview' => '/views/errorview.php',
         'samplestaticview' => '/views/staticview.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
